CREATE TABLE IF NOT EXISTS tb_integrante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    funcao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_do_clube VARCHAR(255) NOT NULL,
    data DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_composicao_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integrante_id bigint,
    time_id bigint,

    CONSTRAINT fk_chord_note_chord
        FOREIGN KEY (time_id)
            REFERENCES tb_time (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_chord_note_note
        FOREIGN KEY (integrante_id)
            REFERENCES tb_integrante (id)
            ON DELETE CASCADE
);